version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "stubs/**",
  "config/**",
  "webroot/**"
]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "php"
enabled = true